In [1]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

[Learn the Basics](intro.html) \|\|
[Quickstart](quickstart_tutorial.html) \|\| **Tensors** \|\| [Datasets &
DataLoaders](data_tutorial.html) \|\|
[Transforms](transforms_tutorial.html) \|\| [Build
Model](buildmodel_tutorial.html) \|\|
[Autograd](autogradqs_tutorial.html) \|\|
[Optimization](optimization_tutorial.html) \|\| [Save & Load
Model](saveloadrun_tutorial.html)

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to [NumPy's](https://numpy.org/) ndarrays, except
that tensors can run on GPUs or other hardware accelerators. In fact,
tensors and NumPy arrays can often share the same underlying memory,
eliminating the need to copy data (see
`bridge-to-np-label`{.interpreted-text role="ref"}). Tensors are also
optimized for automatic differentiation (we\'ll see more about that
later in the [Autograd](autogradqs_tutorial.html) section). If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along!


In [2]:
import torch
import numpy as np

Initializing a Tensor
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [3]:
# Lista de listas 2x2 en Python (dos filas, dos columnas)
data = [[1, 2],[3, 4]]

# De lista de listas a tensor; el tipo se infiere automaticamente
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [ ]:
# De lista de listas a nympy array
np_array = np.array(data)
print(f"numpy array:\n{np_array}")

# De numpy array a tensor de torch
x_np = torch.from_numpy(np_array)
print(f"\ntorch from numpy:\n{x_np}")


"""
La memoria entre los arrays de numpy y los tensores se comparte. No hacer caso de momento,
está explicado más adelante en este mismo notebook del tutorial. Sería como un puntero en C.
"""
np_array[0] = [5, 6]
print(f"\nnumpy array modificado:\n{np_array}")
print(f"\ntorch from numpy después de modificar el array:\n{x_np}")

numpy array:
[[1 2]
 [3 4]]

torch from numpy:
tensor([[1, 2],
        [3, 4]])

numpy array modificado:
[[5 6]
 [3 4]]

torch from numpy después de modificar el array:
tensor([[5, 6],
        [3, 4]])


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [5]:
# Devuelve un tensor de unos con la misma forma y tipo que x_data
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# Devuelve un tensor de numeros aleatorios con la misma forma y tipo que x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4428, 0.5763],
        [0.0351, 0.5743]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [6]:
# Define la forma del tensor: tupla con 2 filas y 3 columnas. La coma final es opcional en tuplas de más de un elemento.
shape = (2,3,)
# Crea un tensor 2x3 con valores aleatorios entre 0 y 1
rand_tensor = torch.rand(shape)
# Crea un tensor 2x3 lleno de unos (1.0).
# Similar a torch.ones_like(x_data) pero sin retener las propiedades de x_data.. Se especifica directamente la forma.
ones_tensor = torch.ones(shape)
# Crea un tensor 2x3 lleno de ceros (0.0)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8157, 0.9777, 0.0104],
        [0.3053, 0.6860, 0.2135]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Attributes of a Tensor
======================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [7]:
# Crea un tensor 3x4 (3 filas y 4 columnas) con valores aleatorios
tensor = torch.rand(3,4)
print(f"Random Tensor: \n {tensor} \n")

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Random Tensor: 
 tensor([[0.4140, 0.7603, 0.0994, 0.3756],
        [0.2765, 0.7111, 0.5897, 0.4236],
        [0.0504, 0.0332, 0.6740, 0.3495]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Over 1200 tensor operations, including arithmetic, linear algebra,
matrix manipulation (transposing, indexing, slicing), sampling and more
are comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the CPU and
[Accelerator](https://pytorch.org/docs/stable/torch.html#accelerators)
such as CUDA, MPS, MTIA, or XPU. If you're using Colab, allocate an
accelerator by going to Runtime \> Change runtime type \> GPU.

By default, tensors are created on the CPU. We need to explicitly move
tensors to the accelerator using `.to` method (after checking for
accelerator availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!


In [8]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(f"Current accelerator: {torch.accelerator.current_accelerator()}")
    print(f"Device tensor is stored on: {tensor.device}")
else:
    print("No accelerator available, running on CPU.")

No accelerator available, running on CPU.


Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [9]:
tensor = torch.ones(4, 4)
print(f'Tensor:', tensor, '\n')
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# Poner a cero la columna 1 (segunda columna) del tensor
tensor[:,1] = 0
print(f"\n Modified Tensor: \n {tensor}")

Tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])

 Modified Tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operator that is subtly different from
`torch.cat`.


In [10]:
# torch.cat concatena sobre una dimension existente (en dim=0 suma filas)
t0 = torch.cat([tensor, tensor], dim=0)
print(f'Tensor t0 - Shape: ', t0.shape, '\n', t0, '\n')

# torch.cat concatena sobre una dimension existente (en dim=1 suma columnas)
t1 = torch.cat([tensor, tensor], dim=1)
print(f'Tensor t1 - Shape: ', t1.shape, '\n', t1, '\n')

# torch.stack crea una nueva dimension; dim=0 agrega un eje al inicio. Apilas como “bloques”. Resultado: forma (2,4,4)
t2 = torch.stack([tensor, tensor], dim=0)
print(f'Tensor t2 - Shape: ', t2.shape, '\n', t2, '\n')

# torch.stack con dim=1 inserta el nuevo eje despues del primer eje. Resultado: forma (4,2,4).
t3 = torch.stack([tensor, tensor], dim=1)
print(f'Tensor t3 - Shape: ', t3.shape, '\n', t3, '\n')

Tensor t0 - Shape:  torch.Size([8, 4]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

Tensor t1 - Shape:  torch.Size([4, 8]) 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]]) 

Tensor t2 - Shape:  torch.Size([2, 4, 4]) 
 tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]]) 

Tensor t3 - Shape:  torch.Size([4, 2, 4]) 
 tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]]]) 



**Arithmetic operations**


In [11]:
# Recordamos el tensor original moficado
print(f"\n Modified Tensor: \n {tensor} \n")

# Multiplicacion matricial entre tensor y su traspuesta.
# ``tensor.T`` returns the transpose of a tensor
# @ = producto matricial (igual que torch.matmul)
print(f"y1 e y2 son iguales, son dos formas de hacer la multipliación matricial \n")
y1 = tensor @ tensor.T
print(f"y1: \n {y1} \n")
y2 = tensor.matmul(tensor.T)
print(f"y2: \n {y2} \n")

#  Crea un tensor nuevo aleatorio (y3) tomando a "y1" como plantilla.
y3 = torch.rand_like(y1)
print(f"y3 before matmul: \n {y3} \n")

# Realiza la multiplicación matricial entre tensor y su traspuesta, pero guarda el resultado en y3 (sobrescribe el valor de y3).
print(f"Una tercera forma de multiplicar. El resutlado es y3, que es igual que y1 e y2\n")
torch.matmul(tensor, tensor.T, out=y3)
print(f"y3 after matmul: \n {y3} \n")


# This computes the element-wise product. z1, z2, z3 will have the same value
# Producto elemento a elemento usando `*` (no es producto matricial).
print(f"Dos formas de hacer un producto elemento a elemento, z1 y z2 son iguales\n")
z1 = tensor * tensor
print(f"z1: \n {z1} \n")
z2 = tensor.mul(tensor)
print(f"z2: \n {z2} \n")

print(f"Una tercera forma de multiplicar elemento a elemento. z3 queda igual que z1 y z2\n")
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z3: \n {z3} \n")


 Modified Tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

y1 e y2 son iguales, son dos formas de hacer la multipliación matricial 

y1: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3 before matmul: 
 tensor([[0.6091, 0.9296, 0.1015, 0.6804],
        [0.6463, 0.2266, 0.3089, 0.3743],
        [0.3643, 0.6706, 0.6874, 0.1000],
        [0.6794, 0.7609, 0.9304, 0.1423]]) 

Una tercera forma de multiplicar. El resutlado es y3, que es igual que y1 e y2

y3 after matmul: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

Dos formas de hacer un producto elemento a elemento, z1 y z2 son iguales

z1: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 

**Single-element tensors** If you have a one-element tensor, for example
by aggregating all values of a tensor into one value, you can convert it
to a Python numerical value using `item()`:


In [12]:
# Recordamos el tensor original moficado
print(f"\n Modified Tensor: \n {tensor} \n")
# Suma todos los elementos del tensor y devuelve un tensor escalar (0-D).
agg = tensor.sum()
# Convierte ese tensor escalar a un valor numerico nativo de Python.
agg_item = agg.item()
# Imprime el valor y su tipo en Python (por ejemplo, float o int).
print(agg_item, type(agg_item))


 Modified Tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

12.0 <class 'float'>


**In-place operations** Operations that store the result into the
operand are called in-place. They are denoted by a `_` suffix. For
example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [ ]:
# Se agrega 5 a cada elemento del tensor de forma in-place (modificando el tensor original).
#  El guion bajo final en add_ es la señal de PyTorch de que es una operación in-place: no crea un tensor nuevo, sino que modifica el existente.
tensor.add_(5)
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")

"""
n = t.numpy() comparte memoria con t porque PyTorch, en CPU, intenta hacer una vista sin copia (zero-copy) sobre el mismo bloque de datos.

En otras palabras, numpy() no crea un arreglo nuevo por defecto: construye un ndarray que apunta al buffer interno del tensor. Por eso, si modificas t, cambia n, y viceversa.

Esto ocurre cuando el tensor es compatible con NumPy (por ejemplo, está en CPU). Si no lo es (p. ej., tensor en GPU), primero hay que mover/copiar datos (t.cpu().numpy()), y ahí ya puede intervenir una copia.

"""

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [16]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [18]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor.


In [ ]:
# Se agrega 1 a cada elemento del tensor t de forma in-place. Dado que n y t comparten memoria, n también se modifica.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
